#!/bin/bash

# Exits immediatley if there is an error
set -o errexit

# Considers pipeline is failed if one command fails. 
set -o pipefail

# Exits script if any uninitialized variable is used
set -o nounset

python manage.py migrate --no-input
python manage.py collectstatic --no-input
exec python manage.py runserver 0.0.0.0:8000